### ISSUE TITLE
Description of repository should be refined

### ISSUE THREAD

**Issue by kbabioch** [cytopia/docker-file-lint#17]
Currently the description of the repository says this:

> Alpine-based Docker image for the very basics of CI against your code files for reproducible usage in CI

This is very abstract and redundant (contains the word CI multiple times). At least for me it is misleading and non-descriptive, so by only reading this description I have no idea what this repository is about.

Therefore I think it should be re-phrased.

My suggest (feel free to change it, though) is the following:

> Alpine-based Docker image to perform generic file checks on your source code in order to improve consistency within your repository (e.g. for easy usage in CI).

**Comment by cytopia** [comment]
@kbabioch thanks. I like it.
